"""
Cliente para subir imágenes a Imgur
"""
import os
import io
import base64
import logging
import requests
from typing import Optional, Dict, Any

logger = logging.getLogger(__name__)


class ImgurClient:
    """Cliente para subir imágenes a Imgur"""
    
    def __init__(self, client_id: str):
        """
        Inicializa el cliente de Imgur
        
        Args:
            client_id: Client ID de la aplicación Imgur
        """
        self.client_id = client_id
        self.base_url = "https://api.imgur.com/3"
        self.headers = {
            'Authorization': f'Client-ID {client_id}',
            'Content-Type': 'application/json'
        }
    
    def upload_image(self, image_buffer: io.BytesIO, title: str = "Plex2Sign") -> Optional[str]:
        """
        Sube imagen a Imgur
        
        Args:
            image_buffer: Buffer con la imagen en bytes
            title: Título para la imagen
            
        Returns:
            URL directa de la imagen o None si falla
        """
        try:
            # Convertir imagen a base64
            image_buffer.seek(0)
            image_data = image_buffer.read()
            image_b64 = base64.b64encode(image_data).decode('utf-8')
            
            # Preparar payload
            payload = {
                'image': image_b64,
                'type': 'base64',
                'title': title,
                'description': f'Generated by Plex2Sign - {title}'
            }
            
            # Hacer petición
            response = requests.post(
                f"{self.base_url}/image",
                json=payload,
                headers=self.headers,
                timeout=10
            )
            
            if response.status_code == 200:
                data = response.json()
                if data.get('success'):
                    image_url = data['data']['link']
                    logger.info(f"Imagen subida exitosamente: {image_url}")
                    return image_url
                else:
                    logger.error(f"Error en respuesta de Imgur: {data}")
                    return None
            else:
                logger.error(f"Error HTTP {response.status_code}: {response.text}")
                return None
                
        except requests.exceptions.RequestException as e:
            logger.error(f"Error de red subiendo a Imgur: {e}")
            return None
        except Exception as e:
            logger.error(f"Error inesperado subiendo a Imgur: {e}")
            return None
    
    def delete_image(self, delete_hash: str) -> bool:
        """
        Elimina imagen de Imgur
        
        Args:
            delete_hash: Hash de eliminación de la imagen
            
        Returns:
            True si se eliminó exitosamente, False en caso contrario
        """
        try:
            response = requests.delete(
                f"{self.base_url}/image/{delete_hash}",
                headers=self.headers,
                timeout=10
            )
            
            if response.status_code == 200:
                data = response.json()
                if data.get('success'):
                    logger.info(f"Imagen eliminada exitosamente: {delete_hash}")
                    return True
            
            logger.error(f"Error eliminando imagen: {response.text}")
            return False
            
        except Exception as e:
            logger.error(f"Error eliminando imagen: {e}")
            return False
    
    def get_account_info(self) -> Dict[str, Any]:
        """
        Obtiene información de la cuenta (si está autenticada)
        
        Returns:
            Diccionario con información de la cuenta
        """
        try:
            response = requests.get(
                f"{self.base_url}/account/me",
                headers=self.headers,
                timeout=10
            )
            
            if response.status_code == 200:
                data = response.json()
                if data.get('success'):
                    return data['data']
            
            return {'error': 'No se pudo obtener información de la cuenta'}
            
        except Exception as e:
            logger.error(f"Error obteniendo info de cuenta: {e}")
            return {'error': str(e)}


def create_imgur_client() -> Optional[ImgurClient]:
    """
    Factory function para crear cliente de Imgur usando variables de entorno
    
    Returns:
        Instancia de ImgurClient o None si falta configuración
    """
    client_id = os.getenv('IMGUR_CLIENT_ID')
    
    if not client_id:
        logger.error("Falta variable de entorno IMGUR_CLIENT_ID")
        return None
    
    return ImgurClient(client_id)
